### ISSUE TITLE
Sample URL does not work

### ISSUE THREAD

**Issue by monty241** [Geonovum/PDOK-NGR-documentatie#14]
On http://pdok-ngr.readthedocs.io/services.html it reads:

...
haalt deze als volgt op:

http://geo.data.nl/ogc-service?
service=WMS/WFS/WMTS/WCS
request=GetCapabilities

This URL does not resolve.

A nslookup on geo.data.nl times out, as well as data.nl. Overheid.nl, nu.nl, etc. resolve. The URL http://geodata.nationaalgeoregister.nl/ahn2/wms?service=wms&request=getmap&layers=ahn2_5m&bbox=13014,306243,286599,623492&width=400&height=500&format=image/png&srs=EPSG:28992 also works fine.

**Comment by ndkv** [comment]
Hi, thanks for submitting an issue!

That is indeed a fake URL meant to demonstrate that each service type supports the `GetCapabilities` request. 

Do you think it is better to use a real URL?

**Comment by monty241** [comment]
Hi, you are welcome.

As an end-user I would either expect a clear note that it is a fake URL, such as either in plain written text a note like "Replace 'geo.data.nl' by xyz which you determine like this..." or a place holder such as "HOSTNAME" instead of geo.data.nl which seems legit but refers to a non-responding/non-resolvable host.

Many platforms offer something like pre-cooked curl statement, swagger or Postman queries, which help to fast understand and analyze the capabilities. For your info, we need raw access to metadata and data because we like to hook the sources up to our SQL engine to allow queries such as:

select ads.addressline, geo.photo 
from addresses@mydatabase ads
join lookupphoto(ads.addressline, ads.city, ads.postalcode)
on 1=1
where ads.city like 'Roermond%'
