### ISSUE TITLE
Vegetatie

### ISSUE THREAD

**Issue by MartijnCCC** [Geonovum/PDOK-NGR-documentatie#15]
Hallo,

Voor het voorspellen van pad verliezen in een telecom netwerk (5-6GHz) gebruiken wij een raytracing model. Voor dit model hebben wij de volgende DTM/DSM data nodig (Nederland):

- DTM, alleen maaiveld hoogte

- DSM, alleen hoogte van gebouwen, bruggen (kunstwerken) en vegetatie (bos e.d.)

Beide datasets moeten in raster formaat zijn of ten minste om te zetten zijn naar raster formaat. 
Is deze data reeds beschikbaar en zo niet, is deze te maken met de data die al dan niet vrij beschikbaar is? 

Groet,
Martijn

**Comment by ndkv** [comment]
Vragen over beschikbaarheid van data kun je het beste op [PDOK Forum](http://forum.pdok.nl) stellen.
