### ISSUE TITLE
WCS aanvraag formaat beperkt

### ISSUE THREAD

**Issue by LaythHuweil** [Geonovum/PDOK-NGR-documentatie#23]
**Probleem**
Ik probeer een WCS aanvraag te sturen  ruwe data binnen te halen. Dit gaat voornamelijk om de AHN 3 type aanvraag. In plaats van een afbeelding waarin de hoogten worden weergegeven in kleuren, zoals bij een WMS aanvraag wil ik de punten als ruwe data aanvragen. Na een aantal keren geprobeerd deze ruwe data binnen te halen heb ik opgemerkt dat in de DescribeCoverage aanvraag alleen de formaten GeoTIFF en TIFF ter beschikking is. Dit is dus geen ruwe data om punten te kunnen creëren voor een bepaalde gebied.

**DescribeCoverage aanvraag**
https://geodata.nationaalgeoregister.nl/ahn3/wcs?service=WCS&version=1.0.0&request=DescribeCoverage&boundingbox=92069,437107,92369,437407&Identifier=ahn3_05m_dtm

**Beschikbare formaten**
http://docs.geoserver.org/stable/en/user/services/wcs/outputformats.html
![image](https://user-images.githubusercontent.com/24441767/37255176-02cf768c-2549-11e8-88de-c14e60faebd6.png)

**Beschikbare formaten ahn wcs**
![image](https://user-images.githubusercontent.com/24441767/37255140-8ad6d724-2548-11e8-8765-e071e0df5170.png)

**Vraag**
Graag zou ik willen weten of dat er helemaal geen ruwe data als webservice aangevraagd kan worden of dat dit via een andere manier aangepakt moet worden?

**Comment by ndkv** [comment]
Zou je je vraag op het [PDOK Forum](https://forum.pdok.nl/) willen stellen? Wat je bescrhijft lijkt een tekortkomingen in de service te zijn. Op het forum zitten ook PDOK developers en product owners die je wellicht sneller/doeltreffender kunnen helpen.
