### ISSUE TITLE
TMS of EPSG:25831:RWS (WGS84) are white

### ISSUE THREAD

**Issue by bwbroersma** [Geonovum/PDOK-NGR-documentatie#26]
See https://geodata.nationaalgeoregister.nl/tiles/service/tms/1.0.0/brtachtergrondkaart/EPSG:25831:RWS/0/0/0.png
![Image of TMS EPSG:25831:RWS 0 0 0](https://geodata.nationaalgeoregister.nl/tiles/service/tms/1.0.0/brtachtergrondkaart/EPSG:25831:RWS/0/0/0.png)
Am I missing something or is it broken?

**Comment by ndkv** [comment]
Thanks for reporting this issue. This repo is, however, concerned with the documentation. Questions and bug reports can be posted on the GeoForum at https://geoforum.nl which is tended by PDOK.
