### ISSUE TITLE
PDOK BAG Geocoder incompatible with 3.4.2 madeira

### ISSUE THREAD

**Issue by bakkerss** [Geonovum/PDOK-NGR-documentatie#29]
I like to install the PDOK BAG Geocoder plugin but it is not compatible with the latest version of QGIS (3.4.2 Madeira). Will this plugin be updated or is this plugin obsolete?

**Comment by ndkv** [comment]
I think it's better to ask this in https://github.com/Lytrix/pdokbaggeocoder. This repo contains only docs, no plugins to be found here. :)
