### ISSUE TITLE
Performance CBS Postcode4 statistieken

### ISSUE THREAD

**Issue by T-Schlepers** [Geonovum/PDOK-NGR-documentatie#36]
Goedemorgen!

Binnen onze applicatie maken we gebruik van de WFS service voor de Postcode4 statistieken van het CBS.
Nu valt mij op dat de performance hiervan vrij traag is, met name de TTFB (Time to first byte).
Zelfs als ik een limiet zet op het aantal records (10) duurt het vrij lang voordat er een response wordt terug gegeven.

Nu is mijn vraag natuurlijk, of dit aan de aanroep ligt zoals ik hem doe, of dat dit iets is van de kant van het nationale georegister.

De URL zoals ik die aanroep is als volgt:

`https://geodata.nationaalgeoregister.nl/cbspostcode4/wfs?request=GetFeature
&service=WFS
&typeName=postcode4:postcode42020
&version=2.0.0
&propertyName=gemiddelde_woz_waarde_woning
&count=10
&outputFormat=json`

En de timing van dat request is als volgt: 
![Timing_WFS_Request](https://user-images.githubusercontent.com/86769082/124578069-284ecb80-de4e-11eb-8923-e55641964341.png)

Kan dit komen door de uitvraag in JSON formaat dat de transformatie van XML naar JSON op de server wat tijd in beslag neemt ?
Alvast bedankt!

**Comment by ndkv** [comment]
Hoi!

Je kan deze vraag beter https://geoforum.nl stellen. PDOK en het CBS lezen mee, zie bijv. https://geoforum.nl/u/cbs/summary. :)
